"""
seed_lawyers.py
===============
Populates lawyers_db.json with 35 real Pakistani law firms / advocates
sourced from:
  • lawzana.com (pages 1-3, April 2026)
  • Uploaded LegalEase dataset (April 2026)

Run once (or with --force to overwrite existing DB):
    python seed_lawyers.py
    python seed_lawyers.py --force

The script is idempotent by default: it only adds lawyers whose
`lawzana_url` is not already present in the DB.
"""

import json
import os
import sys
import uuid
from datetime import datetime

LAWYERS_DB_FILE = "lawyers_db.json"

# ─────────────────────────────────────────────────────────────────────────────
# RAW DATA  (35 verified entries — no fabricated contacts)
# Fields left blank ("") were not publicly listed on their profiles.
# hourly_rate = 0 means "Contact firm for fee schedule"
# ─────────────────────────────────────────────────────────────────────────────
RAW_LAWYERS = [

    # ── KARACHI ──────────────────────────────────────────────────────────────

    {
        "name": "Abdul Karim Khan & Company (AKKC)",
        "specialization": "Civil Law & Corporate",
        "experience_years": 35,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "One of Karachi's most celebrated full-service law firms (est. 1989, 50+ lawyers). Covers criminal, civil, corporate compliance, trademarks, copyrights, and immigration.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/abdul-karim-khan-company/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 1989,
    },
    {
        "name": "Kanasra & Mangi Law Associates",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 34,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🔒",
        "bio": "Established 1990 firm specializing in criminal defense, police matters, and civil litigation across Karachi courts.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/kanasra-mangi-law-firm/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 1990,
    },
    {
        "name": "Karachi Law Empire",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 10,
        "location": "Karachi",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏛️",
        "bio": "Full-service Karachi firm offering a free 15-minute initial consultation. Handles criminal, civil, property, and family matters.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/karachi-law-empire/karachi",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 8,
        "founded": 2014,
    },
    {
        "name": "Legum Law Firm",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 12,
        "location": "Karachi",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Karachi-based criminal defense and civil litigation firm offering a generous free 1-hour initial consultation for new clients.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/legum-law-firm/karachi",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 6,
        "founded": 2012,
    },
    {
        "name": "Hafeez Pirzada Law Associates",
        "specialization": "Criminal Defense & Civil Law",
        "experience_years": 65,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏛️",
        "bio": "One of Pakistan's oldest firms (est. 1959, 50+ lawyers). Deep expertise in criminal defense, civil litigation, and constitutional law across all tiers of courts.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/hafeez-pirzada-law-associates/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 1959,
    },
    {
        "name": "Shahzaib Abdullah & Co. Advocates & Legal Consultants",
        "specialization": "Civil Law / Cybercrime / IP",
        "experience_years": 3,
        "location": "Karachi",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu", "Punjabi", "Sindhi", "Pashto"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💻",
        "bio": "Multi-speciality firm covering civil, criminal, family, cybercrime, and intellectual property law. Offers a free 1-hour initial consultation.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/shahzaib-abdullah-co-advocates-legal-consultants/karachi",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 10,
        "founded": 2023,
    },
    {
        "name": "MAH & Co.",
        "specialization": "Land / Property Law",
        "experience_years": 15,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏠",
        "bio": "Full-service Karachi firm (est. 2010, 15 lawyers) covering corporate matters, property disputes, criminal defense, taxation, and family law.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/mahco/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 15,
        "founded": 2010,
    },
    {
        "name": "Zaman & Co.",
        "specialization": "Land / Property Law & Corporate",
        "experience_years": 4,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu", "Sindhi"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏢",
        "bio": "Modern full-service legal and corporate consultancy (est. 2022, 10 lawyers). Focuses on property, corporate compliance, and dispute resolution.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/zaman-co/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 2022,
    },
    {
        "name": "MSS Associates",
        "specialization": "Banking / Financial Law & Tax",
        "experience_years": 48,
        "location": "Karachi",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏦",
        "bio": "Well-recognised full-service corporate and tax law firm (est. 1976, 20 lawyers). Special expertise in banking & finance, insurance, and tax representation at all courts.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/mss-associates/karachi",
        "website": "",
        "free_consultation": "",
        "team_size": 20,
        "founded": 1976,
    },
    {
        "name": "Lalani & Associates",
        "specialization": "Immigration / Citizenship Law",
        "experience_years": 33,
        "location": "Karachi",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "✈️",
        "bio": "Pakistan's leading immigration consultants (est. 1992, 50 lawyers). Specialise in citizenship & residency programs for Canada, USA, UK, Australia, Turkey and more.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Sindh Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/lalani-associates/karachi",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 50,
        "founded": 1992,
    },

    # ── LAHORE ───────────────────────────────────────────────────────────────

    {
        "name": "Asma Lawyers In Pakistan",
        "specialization": "Family Law / Criminal Defense",
        "experience_years": 22,
        "location": "Lahore",
        "availability": "WhatsApp available",
        "languages": ["English", "Urdu", "Punjabi"],
        "rating": 5.0,
        "review_count": 2,
        "hourly_rate": 0,
        "emoji": "👩‍⚖️",
        "bio": "Led by Asma Tanveer Randhawa (est. 2003, 9 lawyers). Handles court appearances, property, family, divorce, child custody, NADRA documentation, and guardianship.",
        "contact_email": "",
        "contact_phone": "+92 300-6622189",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/asma-best-lawyers-in-pakistan/lahore",
        "website": "https://www.asmalawyersinpakistan.com",
        "free_consultation": "",
        "team_size": 9,
        "founded": 2003,
    },
    {
        "name": "Frasat & Partners The Law Firm",
        "specialization": "Criminal Defense / Civil Litigation",
        "experience_years": 20,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Reputable Lahore firm with a broad practice covering criminal defense, civil disputes, family law, and corporate matters.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/frasat-partners-the-law-firm/lahore",
        "website": "https://www.frasatandpartners.com",
        "free_consultation": "",
        "team_size": 10,
        "founded": 2004,
    },
    {
        "name": "Saeed and Moeez Law Firm",
        "specialization": "Land / Property Law & IP",
        "experience_years": 9,
        "location": "Lahore",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏠",
        "bio": "Leading experts in property, family, intellectual property, taxation, and cybercrime law (est. 2017, 8 lawyers).",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/saeed-and-moeez-law-firm/lahore",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 8,
        "founded": 2017,
    },
    {
        "name": "Sadiq Law Associates",
        "specialization": "Land / Property Law",
        "experience_years": 28,
        "location": "Lahore",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏠",
        "bio": "Experienced Lahore property law firm (est. 1997) offering free 15-minute initial consultations. Handles land acquisition, title disputes, and real estate transactions.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/sadiq-law-associates/lahore",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 6,
        "founded": 1997,
    },
    {
        "name": "Qadeer Ahmad Siddiqi Law Associates",
        "specialization": "Family Law / Child Custody",
        "experience_years": 57,
        "location": "Lahore",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "👨‍👩‍👧",
        "bio": "Trusted family law advocates since 1968 (25 lawyers). Led by Fahad Ahmad Siddiqi, specialising in child custody, divorce, khula, and cross-border family disputes.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/child-custody-law-services/lahore",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 25,
        "founded": 1968,
    },
    {
        "name": "Jamila Law Associates",
        "specialization": "Islamic / Sharia Law",
        "experience_years": 25,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "☪️",
        "bio": "Well-established Sharia and family law firm (est. 2000, 50 lawyers). Handles Islamic finance, inheritance under Muslim personal law, and family disputes.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/jamila-law-associates/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 2000,
    },
    {
        "name": "First Women Law Firm",
        "specialization": "Islamic / Sharia Law & Women Rights",
        "experience_years": 12,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "👩‍⚖️",
        "bio": "Pakistan's premier all-women law firm (est. 2014, 6 lawyers). Focus on women's rights, family law, Sharia-based divorce, and domestic violence cases.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/first-women-law-firm/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 6,
        "founded": 2014,
    },
    {
        "name": "MR Legal Inn",
        "specialization": "Banking / Financial Law & Corporate",
        "experience_years": 11,
        "location": "Lahore",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu", "Arabic", "French"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏦",
        "bio": "Full-service firm (est. 2015, 8 lawyers) specialising in banking, corporate, and international business law. Advises local and international clients across Pakistan.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/mr-legal-inn/lahore",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 8,
        "founded": 2015,
    },
    {
        "name": "Legis Inn Attorneys & Corporate Consultants",
        "specialization": "Banking / Financial Law & Corporate",
        "experience_years": 18,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💼",
        "bio": "Pakistan-based full-service law firm (est. 2008, 50 lawyers) providing internationally-accustomed legal services across Asia Pacific, Europe, and the Middle East.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/legis-inn-attorneys-corporate-consultants/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 2008,
    },
    {
        "name": "24Justice Online Lawyers",
        "specialization": "Banking / Financial Law & Corporate",
        "experience_years": 10,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🌐",
        "bio": "Pakistan's first AI-powered legal platform (est. 2016, 50 lawyers). Accredited lawyers providing clear, reliable legal services online across all practice areas.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/24justice-online-lawyers/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 2016,
    },
    {
        "name": "Lexum Law Firm Lahore",
        "specialization": "Criminal Defense / Family Law",
        "experience_years": 13,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Founded 2013 (20 lawyers). Affordable legal services online and in court — family cases, property, criminal trials, immigration, and FIA matters.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/lexum-law-firm-lahore/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 20,
        "founded": 2013,
    },
    {
        "name": "Law Society Pakistan The Law Firm (Bajwa Law Chambers)",
        "specialization": "Civil Law & General Practice",
        "experience_years": 63,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏛️",
        "bio": "Sister concern of Bajwa Law Chambers (est. 1962, 50+ lawyers). One of Punjab's oldest and most experienced full-service law firms with Advocate Supreme Court representation.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/law-society-pakistan-the-law-firm/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 50,
        "founded": 1962,
    },
    {
        "name": "Al Noor Law",
        "specialization": "Family Law & Divorce",
        "experience_years": 8,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "👨‍👩‍👧",
        "bio": "Compassionate divorce and family law specialists (est. 2018, 5 lawyers). Handles khula, divorce, child custody, and women's rights with emotional support.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/al-noor-law/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 5,
        "founded": 2018,
    },
    {
        "name": "Khalid Zafar Associates Corporate Lawyers",
        "specialization": "Corporate & Commercial Law",
        "experience_years": 25,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💼",
        "bio": "Expert in drafting, handling, and negotiating all types of contracts (est. 2000, 10 lawyers). Specialises in EPC, OEM, FIDIC-type contracts, and international commercial law.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/khalid-zafar-associates-corporate-lawyers/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 2000,
    },
    {
        "name": "Codex & Co. Intellectual Property",
        "specialization": "Intellectual Property Law",
        "experience_years": 38,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "©️",
        "bio": "Boutique IP and corporate law firm (est. 1987, 10 lawyers) combining legal attorneys with IT experts. Specialist in anti-piracy in Pakistan and India.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/codex-co-intellectual-property/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 1987,
    },
    {
        "name": "Rao & Virk International Law Firm",
        "specialization": "Family Law / International Law",
        "experience_years": 6,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu", "Norwegian"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🌍",
        "bio": "International firm (est. 2020) for overseas Pakistanis and foreigners. Strong ties to Norway and the UK. Handles family, civil, criminal, and corporate matters.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/rao-virk-international-law-firm/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 2020,
    },
    {
        "name": "Legal Bridge LLP",
        "specialization": "Civil Law & Corporate",
        "experience_years": 5,
        "location": "Lahore",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🌉",
        "bio": "Innovative Lahore firm (est. 2021, 10 lawyers) building long-term client relationships. Redefining legal service delivery through modern models and professional ethics.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/legal-bridge-llp/lahore",
        "website": "",
        "free_consultation": "",
        "team_size": 10,
        "founded": 2021,
    },
    {
        "name": "Saleem & Sarim Law Firm",
        "specialization": "Criminal Defense / Civil Litigation",
        "experience_years": 11,
        "location": "Lahore",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu", "Hindi"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Established 2015 (19 lawyers). Specialists in their own fields, with landmark High Court judgments. Operates across Punjab and major Pakistani cities. Online services available.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/saleem-sarim-law-firm-r/lahore",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 19,
        "founded": 2015,
    },
    {
        "name": "MAK Legal",
        "specialization": "Intellectual Property Law",
        "experience_years": 11,
        "location": "Lahore",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "©️",
        "bio": "One of Pakistan's leading IP rights firms (est. 2015, 13 lawyers). Prestigious client base with senior associates and reputed lawyers around the globe.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/mak-legal/lahore",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 13,
        "founded": 2015,
    },

    # ── ISLAMABAD / RAWALPINDI ────────────────────────────────────────────────

    {
        "name": "Alvi Law Associates",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 22,
        "location": "Islamabad",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🔒",
        "bio": "Established 2004 with offices in both Islamabad and Rawalpindi. Specialises in criminal defense, police matters, and civil litigation.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/alvi-law-associates/islamabad-islamabad",
        "website": "",
        "free_consultation": "",
        "team_size": 8,
        "founded": 2004,
    },
    {
        "name": "Legal Dispute Expounders",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 10,
        "location": "Islamabad",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Islamabad-based criminal and civil dispute specialists offering a free 15-minute initial consultation for all new clients.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/legal-disputes-expounders/islamabad-islamabad",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 6,
        "founded": 2014,
    },
    {
        "name": "Ahmed Ali Dewan & Co.",
        "specialization": "Civil Law & Corporate",
        "experience_years": 26,
        "location": "Islamabad",
        "availability": "Free 1-hour consultation",
        "languages": ["English", "Urdu", "Sindhi"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏛️",
        "bio": "One of Islamabad's leading law firms (est. 2000, 22 lawyers). Expert legal advice across a wide spectrum including civil, corporate, family, and property law.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/ahmed-ali-dewan-co/islamabad-islamabad",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 22,
        "founded": 2000,
    },
    {
        "name": "Alam & Alam",
        "specialization": "Civil Law & Financial Consultancy",
        "experience_years": 16,
        "location": "Islamabad",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💼",
        "bio": "Legal and financial consultancy co-founded by Barrister Muhammad Hassan Alam and Muhammad Hussain Alam FCA, ACCA (est. 2010, 10 lawyers). Combines legal and financial expertise.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/alam-alam/islamabad-islamabad",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 10,
        "founded": 2010,
    },
    {
        "name": "M Bilal Advocates, Corporate & Tax Consultants",
        "specialization": "Banking / Financial Law & Tax",
        "experience_years": 8,
        "location": "Islamabad",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu", "Arabic", "Japanese"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💰",
        "bio": "Comprehensive legal services firm (est. 2018, 20 lawyers) specialising in corporate law, tax, family law, banking, and dispute resolution. Active on Lawzana Q&A.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/m-bilal-advocates-corporate-tax-consultants/islamabad-islamabad",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 20,
        "founded": 2018,
    },
    {
        "name": "Mehar Legal and Business Consultant",
        "specialization": "Civil Law & General Practice",
        "experience_years": 14,
        "location": "Islamabad",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏛️",
        "bio": "Full-service firm (est. 2012, 7 lawyers) with network across all Pakistani cities. Provides civil, criminal, banking, and Supreme Court-level litigation services.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Islamabad Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/mehar-legal-business-consultant/islamabad-islamabad",
        "website": "",
        "free_consultation": "",
        "team_size": 7,
        "founded": 2012,
    },
    {
        "name": "Qadeer Ahmad Siddiqi Law Associates (Rawalpindi)",
        "specialization": "Family Law / Child Custody",
        "experience_years": 57,
        "location": "Rawalpindi",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "👨‍👩‍👧",
        "bio": "Rawalpindi office of this trusted family law firm (est. 1968, 25 lawyers). Led by Fahad Ahmad Siddiqi, covering child custody, divorce, and cross-border family disputes.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Rawalpindi Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/child-custody-law-services/rawalpindi",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 25,
        "founded": 1968,
    },

    # ── FAISALABAD ────────────────────────────────────────────────────────────

    {
        "name": "Advocate High Court (Faisalabad)",
        "specialization": "Land / Property Law & Civil",
        "experience_years": 12,
        "location": "Faisalabad",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🏠",
        "bio": "Faisalabad firm (est. 2014, 12 lawyers) expert in civil, criminal, family, banking, cyber, CNIC, guardianship, immigration, and court marriage matters.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/advocate-high-court/faisalabad",
        "website": "",
        "free_consultation": "",
        "team_size": 12,
        "founded": 2014,
    },
    {
        "name": "Shahid Hamid Law Associates",
        "specialization": "Tax Law & Civil Litigation",
        "experience_years": 8,
        "location": "Faisalabad",
        "availability": "Free 15-min consultation",
        "languages": ["English", "Urdu", "Hindi"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💰",
        "bio": "Expert Faisalabad lawyers (est. 2018, 6 lawyers). Wide-range services: income tax, sales tax, civil, criminal, family, labour, corporate, IP, and constitutional law.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/shahid-hamid-law-associates/faisalabad",
        "website": "",
        "free_consultation": "15 minutes",
        "team_size": 6,
        "founded": 2018,
    },

    # ── JHANG ─────────────────────────────────────────────────────────────────

    {
        "name": "Ghallu Law Firm",
        "specialization": "Civil Law & Family Law",
        "experience_years": 20,
        "location": "Jhang City",
        "availability": "Contact firm",
        "languages": ["Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "⚖️",
        "bio": "Multi-disciplinary firm (est. 2006, 5 lawyers) in Jhang City covering criminal, civil, and family law — providing comprehensive legal advocacy.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "Punjab Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/ghallu-law-firm/jhang-city",
        "website": "",
        "free_consultation": "",
        "team_size": 5,
        "founded": 2006,
    },

    # ── MUZAFFARABAD (AJK) ───────────────────────────────────────────────────

    {
        "name": "Gillani Law Chambers Muzaffarabad",
        "specialization": "Police Law / Criminal Defense",
        "experience_years": 8,
        "location": "Muzaffarabad",
        "availability": "Contact firm",
        "languages": ["English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "🔒",
        "bio": "AJK-based criminal defense and civil litigation firm (est. 2018). Serves Muzaffarabad and surrounding Azad Kashmir districts.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "AJK Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/gillani-law-chambers-muza/muzaffarabad",
        "website": "",
        "free_consultation": "",
        "team_size": 4,
        "founded": 2018,
    },

    # ── SWABI (KPK) ───────────────────────────────────────────────────────────

    {
        "name": "TaxationPk",
        "specialization": "Tax Law & Financial Advisory",
        "experience_years": 6,
        "location": "Swabi",
        "availability": "Free 1-hour consultation",
        "languages": ["Pashto", "English", "Urdu"],
        "rating": 0.0,
        "review_count": 0,
        "hourly_rate": 0,
        "emoji": "💰",
        "bio": "Leading tax preparation and advisory firm (est. 2020, 26 lawyers). Covers all aspects of Pakistani taxation including corporate, income, and sales tax compliance.",
        "contact_email": "",
        "contact_phone": "",
        "bar_council": "KPK Bar Council",
        "bar_number": "",
        "verified": True,
        "lawzana_url": "https://lawzana.com/lawyer/taxationpk/swabi",
        "website": "",
        "free_consultation": "1 hour",
        "team_size": 26,
        "founded": 2020,
    },
]

# ─────────────────────────────────────────────────────────────────────────────

def load_db() -> dict:
    if os.path.exists(LAWYERS_DB_FILE):
        with open(LAWYERS_DB_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_db(db: dict):
    with open(LAWYERS_DB_FILE, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
    print(f"✅  Saved {len(db)} lawyers to {LAWYERS_DB_FILE}")


def existing_urls(db: dict) -> set:
    return {v.get("lawzana_url", "") for v in db.values()}


def build_record(raw: dict) -> dict:
    now = datetime.utcnow().isoformat()
    new_id = str(uuid.uuid4())
    return {
        "id": new_id,
        "name": raw["name"],
        "specialization": raw["specialization"],
        "experience_years": raw["experience_years"],
        "location": raw["location"],
        "availability": raw["availability"],
        "languages": raw["languages"],
        "rating": raw["rating"],
        "review_count": raw["review_count"],
        "hourly_rate": raw["hourly_rate"],
        "currency": "PKR",
        "emoji": raw["emoji"],
        "bio": raw["bio"],
        "contact_email": raw["contact_email"],
        "contact_phone": raw["contact_phone"],
        "bar_council": raw["bar_council"],
        "bar_number": raw["bar_number"],
        "verified": raw["verified"],
        "active": True,
        # Extra metadata (not in LawyerPublic schema — stored for admin use)
        "lawzana_url": raw.get("lawzana_url", ""),
        "website": raw.get("website", ""),
        "free_consultation": raw.get("free_consultation", ""),
        "team_size": raw.get("team_size", 0),
        "founded": raw.get("founded", 0),
        "created_at": now,
        "updated_at": now,
    }


def main():
    force = "--force" in sys.argv
    db = load_db()

    if force:
        print("⚠️  --force flag: clearing existing DB …")
        db = {}

    urls = existing_urls(db)
    added = 0
    skipped = 0

    for raw in RAW_LAWYERS:
        url = raw.get("lawzana_url", "")
        if url and url in urls and not force:
            print(f"  ⏩  Skip (exists): {raw['name']}")
            skipped += 1
            continue
        record = build_record(raw)
        db[record["id"]] = record
        urls.add(url)
        added += 1
        print(f"  ➕  Added: {raw['name']} ({raw['location']})")

    save_db(db)
    print(f"\n📊  Summary: {added} added | {skipped} skipped | {len(db)} total in DB")


if __name__ == "__main__":
    main()
